### ISSUE TITLE
Question regarding the hard-coded 65x65 search frame

### ISSUE THREAD

**Issue by wenxuanliang** [flatironinstitute/CaImAn-MATLAB#100]
Please note that the developer of this package is on leave until January 2019 and might not be able to support you.

For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

In line 68-74 of determine_search_location.m, the region of interest is limited to a 65x65 square centering at the center of mass (CoM) of the initilized spatial component.
When working on dendritic data, sometimes a dendrite can extend across the entire patch, where the CoM-centered 65x65 square might not contain the dendrite.

**Comment by epnev** [comment]
@wenxuanliang Thanks for this observation. I just updated the code to explore the full FOV 9e524e29f17d35db3c79a87de32209c7dccda186
