### ISSUE TITLE
Potential improvement on construct_patches.m

### ISSUE THREAD

**Issue by wenxuanliang** [flatironinstitute/CaImAn-MATLAB#101]
Please note that the developer of this package is on leave until January 2019 and might not be able to support you.

For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

In the current implementation, the starting indices are constructed as line 31
x_start = 1:siz(1)-overlap(1):sizY(1);  
An potential improvement via x_start = 1:siz(1)-overlap(1):sizY(1)-overlap(1) can save an 
unnecessary small patch for some cases.

To see that, denote entire image size sizY(1) = N, patch size siz(1) by P, and overlap between adjacent patches overlap(1) by S. Obvious, the largest starting pixel index should be no less than image size N – P + 1, i.e. we need to found the smallest m, so that 1 + m×S >= N-P+1. For such smallest m, we have 1 + (m+1)×S >= N-P+1+S, therefore we can limit 1 + m×S <= N-P+S to avoid the unnecessary (m+1) case. So in MATLAB language, setting starting indices by 1:S:N-OVL as aboe should be good. 
For example, N = 384, P = 144, and S = 48, the original 1:S:N gives [1, 49, 97, 145, 193, 241, 289, 337], while the following checking step (line 33-36) eliminates the starting index = 337 case, the 289:384 patch (length = 96) remains, and it is totally contained in the 241:384 (length = 144) patch here. If we do 1:S:N-OVL = 1:48:288 instead, the 289:384 patch won’t show up.

Since this starting indices calculation applies to 2D or 3D, reducing the patch number from 7x7 = 49 to 6x6=36 can still decenlty cut down the computational load.

**Comment by epnev** [comment]
I'm not sure I understand. The starting indeces will be in `1:P-S:N` and not `1:S:N`. With your numbers:
```
>> patches = cell2mat(construct_patches([384, 384], [144, 144], [48, 48]))

patches =

     1   144     1   144
     1   144    97   240
     1   144   193   336
     1   144   289   384
    97   240     1   144
    97   240    97   240
    97   240   193   336
    97   240   289   384
   193   336     1   144
   193   336    97   240
   193   336   193   336
   193   336   289   384
   289   384     1   144
   289   384    97   240
   289   384   193   336
   289   384   289   384
```
and stays the same after the change you propose. I think your suggestion make sense but can you give an example where it proves to be beneficial?

**Comment by wenxuanliang** [comment]
Sorry I typed it wrong. S should be the stride size, i.e. S = patch size P - overlap.

**Comment by epnev** [comment]
I see. I added your change here a02d0dda32c519d9929c6bb1cdfab66a619485b2
However, I would not recommend such large values of overlap since that already increases the computational load significantly. Thanks

**Comment by wenxuanliang** [comment]
Thank you, Dr. Pnevmatikakis. I agree with you, and I set this large overlap only trying to capture extended dendrites that stretches across the entire FOV.
