### ISSUE TITLE
Undefined function or variable 'NoRMCorreSetParms'.  

### ISSUE THREAD

**Issue by tomatoccoo** [flatironinstitute/CaImAn-MATLAB#103]
- **when I run run_pipeline.m on my own data, I got the error, and can't find the NoRMCorreSetParms function in all the folder**

- "Undefined function or variable 'NoRMCorreSetParms'"

**Comment by epnev** [comment]
@tomatoccoo The error means that the [NoRMCorre](https://github.com/flatironinstitute/normcorre) package is either not installed or not in your MATLAB path.

**Comment by dlogan** [comment]
Thanks for this answer, which works for me as well, however I suggest you add NoRMCorre package to the list of dependencies to avoid such issues.
