### ISSUE TITLE
Error in run_pipeline 

### ISSUE THREAD

**Issue by jic0101** [flatironinstitute/CaImAn-MATLAB#106]
Hello,

I have been trying run_pipeline.m using a tiff file. I got error messages as below:

An UndefinedFunction error was thrown on the workers for 'Undefined function 'findpeaks' for input arguments of type 'double'.'.  This might be because the
file containing 'Undefined function 'findpeaks' for input arguments of type 'double'.' is not accessible on the workers. Use addAttachedFiles(pool, files)
to specify the required files to be attached.  For more information, see the documentation for 'parallel.Pool/addAttachedFiles'.

Error in run_pipeline (line 127)
[A,b,C,f,S,P,RESULTS,YrA] = run_CNMF_patches(data,K,patches,tau,0,options);  % do not perform deconvolution here since

Caused by:
    Error using classify_comp_corr (line 44)
    Undefined function 'findpeaks' for input arguments of type 'double'.

Thank you very much for your help in advance!
Changyi

**Comment by epnev** [comment]
`findpeaks` is a function which is included in the signal processing toolbox and is needed to run CaImAn-MATLAB. You'll need to install this or switch to the python version which in general works better (and does not require any licenses).
