### ISSUE TITLE
Trouble using ROI_GUI

### ISSUE THREAD

**Issue by CharlieOC19** [flatironinstitute/CaImAn-MATLAB#107]
Please note that the developer of this package is on leave until January 2019 and might not be able to support you.
  
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

- **Describe the issue that you are experiencing**

I'm trying to modify the components selection because some of the components are not neurons, so I tried using ROI_GUI (From line 155 to 161) but there is a variable that doesn't exist called ROIvars. I try run the GUI for apart but I failed.

Is there any way I can solve this?

Can I do something to choose the components? How can I add components ?
Thanks

- **Copy error log below**
Undefined function or variable 'ROIvars'.

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@CharlieOC19 Unfortunately the GUI is outdated and not supported at the moment.
