### ISSUE TITLE
paste centroids of neurons as a ROI_list

### ISSUE THREAD

**Issue by LoOthar** [flatironinstitute/CaImAn-MATLAB#76]
Hi,
I tried to implement a list of coordinates as a ROI list using the _greedyROI_ file.  Therefore, I added a field 'ROI_list' to the structure P in _run_CNMF_patches_. In line 324 I added this code:.

`coord = load('coordinates.mat');
    P.ROI_list = coord.coordinates;`

Since _initialize_components_ calls _greedyROI_ in line 124 and checks for a ROI_list in line 117 it should be still possible to use it. But the identified components exceed the number of marked neurons in the coordinate file and do not resemble the marked points. It seems as it does ignore the ROI list.

Do you have any idea why? Or do you know a different way to implement custom centroids?

Best,
Simon

**Comment by epnev** [comment]
@LoOthar I don't believe that ROI_list will work with `run_CNMF_patches`. The idea behind  `run_CNMF_patches` is to break the FOV into patches and search independently in each of them and the ROI_list will not get remapped into the coordinates of each patch. You can use it when you run the code in a single patch, use demonstrated in [`demo_script.m`](https://github.com/flatironinstitute/CaImAn-MATLAB/blob/master/demo_script.m) or [`demo_script_class.m`](https://github.com/flatironinstitute/CaImAn-MATLAB/blob/master/demo_script.m). In the latter, you'll probably need to paste the coordinates after the pre-processing.

**Comment by LoOthar** [comment]
@epnev thank you very much for the fast reply. I will then use either the one or the other, depending on what fits my data better.
