### ISSUE TITLE
Memory error using demo_patches

### ISSUE THREAD

**Issue by hubhubhang** [flatironinstitute/CaImAn-MATLAB#81]
Hi develope, 

I ran into a problem when using the "demo_patch.m".
![memory error p1](https://user-images.githubusercontent.com/13278555/45924115-4967ec80-beac-11e8-9163-2fb6da60daba.PNG)
![memory error p2](https://user-images.githubusercontent.com/13278555/45924116-5a186280-beac-11e8-92b1-3aeccaafca6a.PNG)

My data is 512x 512x 6810. My patch_size is [32,32] and overlap is [6,6].
Is my time axis too long or my field of view too larger?  or the patch_size is too small?
Any insight / quick solution?

Thank you

**Comment by epnev** [comment]
@hubhubhang The script failed at computing the correlation image which is only used for visualization. How much memory do you have?

You can try reducing the variables `batch_size` and `min_batch_size` in the [`correlation_image_max`](https://github.com/flatironinstitute/CaImAn-MATLAB/blob/master/utilities/correlation_image_max.m) function, e.g., to value 500. It should go through without problems.

**Comment by epnev** [comment]
@hubhubhang Good to hear. In general I'd recommend to use more memory for your analysis. You can ignore the warning messages.
