### ISSUE TITLE
process multiple sessions using  run_pipeline

### ISSUE THREAD

**Issue by chunyueli** [flatironinstitute/CaImAn-MATLAB#83]
Dear Pnevmatikakis，

Thanks very much for developing this useful toolbox. 

I record multiple calcium imaging sessions a day. The field of view is very similar across sessions. However, the baseline intensity value of sessions could different. I know your code (run_pipeline.m) can process many sessions together. I’m wondering if the changed baseline values will affect the inferring results, like spatial footprint and temporal activity. Are there any shortcomings compared to process sessions separately? thanks very much!

Best regards,
Yue

**Comment by epnev** [comment]
@chunyueli You should be able to do this, provided you don't combine the results from the different sessions and then try to deconvolve. For example in the [run_pipeline.m script](https://github.com/flatironinstitute/CaImAn-MATLAB/blob/master/run_pipeline.m#L200) when you reach the line 200, you will need to save the results separately and then deconvolve. If you think that your FOV has changed significantly between the different sessions then its best to analyze them separately altogether and then register the ROIs of the different sessions. Let me know if that helps.

**Comment by chunyueli** [comment]
Thanks very much for your reply! 
Before I feed my data into run_pipeline, I've done the FOV alignment. The FOV is very similar across sessions.  I compared the results obtained by run_pipeline and demo_script. it seems that individually process single session can get better results. 

I want the same neuron to have a unique ID in different sessions (recorded on the same day). Here is what I do: firstly, I get the center coordinates of each potential neuron from a 2000 frame stack by using initialize_components function. Because all session has the same FOV, I use these coordinates as the initial value of ROI_list and feed this list into the greedyROI function for all sessions. Then I record the deleted ROI index during update spatial components. I also canceled the order_ROIs function. 
I done this because the register_ROI only map two sessions. However, I record more than ten sessions a day.

Do you have any suggestions about the above method? I just finished the coding today, still waiting for the final results.

Finally, your code helps me a lot! I really appreciate your work!

**Comment by epnev** [comment]
@chunyueli Our python code has a function for registering more than two sessions at a time. If you know a bit of python you can export your results from each session there and use it. Will that work for you?

**Comment by chunyueli** [comment]
yes, that helps. Thanks a lot!
