### ISSUE TITLE
Processing many .tif files

### ISSUE THREAD

**Issue by PhantomSpike** [flatironinstitute/CaImAn-MATLAB#86]
Hi,

Firstly, thank you very much for developing this software, it is fantastic!

I am trying to get started and am unsure about something. I am collecting mostly _in vivo_ 2-photon GCaMP6f/m somatic data with a Thorlabs microscope and using ScainImage Matlab software. The collection software/hardware cannot save more than 900 frames in a single file I end up with a bunch of .tif files. Let's say my stimulus is 9,000 frames so I have 10x900_frames_tif_files. 

If I want to process them together, should I:

1) Concatenate them into a single .tif/other format file and then run through the CaImAn pipeline

**OR**

2) Run them all separately as they are in for loops in the run_pipeline:

e.g.
for i = 1:numFiles
Some processing of i
end

Where each file is one of the aforementioned .tif files?

Another general question is, am I loosing processing power/functionality by suing the Matlab implementation of CaImAn instead of the Python one?  I am not as experienced with Python so would like to stick to Matlab for now if possible.

Thanks!

Alex

**Comment by epnev** [comment]
@PhantomSpike The [`run_pipeline`](https://github.com/flatironinstitute/CaImAn-MATLAB/blob/master/run_pipeline.m#L9) script shows how to process multiple files at once. You don't need to concatenate them unless each file is very short (e.g., less than <300-500 frames).
