### ISSUE TITLE
demo_endoscope

### ISSUE THREAD

**Issue by zoranne** [flatironinstitute/CaImAn-MATLAB#93]
Hi, I'm running into an error when running demo_endoscope.m.

Error occurs on line 73:

`Reference to non-existent field "detrend_method".
Error in Sources2D/InitComponents_endoscope (line 26)
detrend_method = obj.options.detrend_method; `

Any help appreciated! Cheers, Anne

**Comment by epnev** [comment]
@zoranne I suggest you use the [CNMF-E](https://github.com/zhoupc/CNMF_E) package for an up-to-date endoscope data analysis in MATLAB. The package here is mostly for 2p data.
