### ISSUE TITLE
error in demo_endoscope

### ISSUE THREAD

**Issue by elizabethpereida** [flatironinstitute/CaImAn-MATLAB#94]
Please note that the developer of this package is on leave until January 2019 and might not be able to support you.

For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

- **Describe the issue that you are experiencing**
Hello
I've problem with the installation 
I try to use demo_endoscope.m and I installed all function in my pc but showed error 

- **Copy error log below**

Error using Sources2D/reshape
Too many input arguments.
Error in demo_endoscope (line 52)
Y = neuron.reshape(Y,1);       % convert a 3D video into a 2D matrix 

I hope that you can help me
thanks
- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@elizabethpereida I suggest you use the [CNMF-E](https://github.com/zhoupc/CNMF_E) package for an up-to-date endoscope data analysis in MATLAB. The package here is mostly for 2p data.
