### ISSUE TITLE
run_pipeline error - Undefined function or variable 'NoRMCorreSetParms'.

### ISSUE THREAD

**Issue by tochenan** [flatironinstitute/CaImAn-MATLAB#96]
Hello, I was trying to analyze the calcium imaging signals using the run_pipeline function but found the following problems and I am a bit confused about the error message generated.
- **Describe the issue that you are experiencing**

- **Copy error log below**
the error code goes like this:

Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 65000 (0xfde8) encountered.'

    In Tiff (line 657)

  In read_file (line 28)
  In run_pipeline (line 10)
  In run (line 91)
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 65001 (0xfde9) encountered.'

    In Tiff (line 657)

  In read_file (line 28)
  In run_pipeline (line 10)
  In run (line 91)
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 65002 (0xfdea) encountered.'

    In Tiff (line 657)

  In read_file (line 28)
  In run_pipeline (line 10)
  In run (line 91)
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 65003 (0xfdeb) encountered.'

    In Tiff (line 657)

  In read_file (line 28)
  In run_pipeline (line 10)
  In run (line 91)
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 65000 (0xfde8) encountered.'

    In Tiff/setDirectory (line 1293)

  In read_file (line 32)
  In run_pipeline (line 10)
  In run (line 91)
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 65001 (0xfde9) encountered.'

    In Tiff/setDirectory (line 1293)

  In read_file (line 32)
  In run_pipeline (line 10)
  In run (line 91)
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 65002 (0xfdea) encountered.'

    In Tiff/setDirectory (line 1293)

  In read_file (line 32)
  In run_pipeline (line 10)
  In run (line 91)
Warning: TIFF library warning - 'TIFFReadDirectory:  Unknown field with tag 65003 (0xfdeb) encountered.'

    In Tiff/setDirectory (line 1293)

  In read_file (line 32)
  In run_pipeline (line 10)
  In run (line 91)
Undefined function or variable 'NoRMCorreSetParms'.

Error in run_pipeline (line 24)
options_mc = NoRMCorreSetParms('d1',FOV(1),'d2',FOV(2),'grid_size',[128,128],'init_batch',200,...

Thank you very much.

Mingran :)

**Comment by epnev** [comment]
@tochenan The warning is just telling you that there is a tag in your TIFF file that cannot be interpreted. It shouldn't affect the processing in any way. 

The error means that the [NoRMCorre](https://github.com/flatironinstitute/normcorre) package is either not installed or not in your MATLAB path.
