### ISSUE TITLE
Question on PSD Calculation

### ISSUE THREAD

**Issue by wenxuanliang** [flatironinstitute/CaImAn-MATLAB#98]
Please note that the developer of this package is on leave until January 2019 and might not be able to support you.

For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

In get_noise_fft, the power spectrum density of the noise is calculated via 
psdx = (1/(Fs*N)) * abs(xdft).^2;
I don't understand why the normalization factor (1/(Fs*N)) is not squared also. 
Suppose we have a noise component with amplitude A_m at normalized frequency 2*pi/N*m, i.e. noise_component_m (n) = A_m * cos( 2*pi/N * m * n + theta), then it will result in an fft amplitude of A_m * N/2 at +/- 2*pi/N*m, respectively. 
Therefore, to estimate the noise power density, i.e. A_m^2 here, shouldn't we square (1/(Fs*N)) also?

**Comment by epnev** [comment]
@wenxuanliang 
The code follows closely the example provided by Mathworks [here](https://www.mathworks.com/help/signal/ug/power-spectral-density-estimates-using-fft.html).

**Comment by wenxuanliang** [comment]
Thank you for your swift response.
The example code might not be 100% error-free. In that example code, if you change 
t = 0:1/Fs:1-1/Fs; 
to 
t = 0:1/Fs:10-1/Fs;
i.e. extending the sampling time by 10 times, the result increase by 10dB. So the power density calculation scales with sample length (assuming fixed sampling rate), which doesn't make much sense to me.

However, I noticed in the Neuron 2016 paper, the constraints for (P-T), (P-S), (P-CD) are all || ... || <= \sigma * \sqrt(T). I guess such PSD calculation matches these constrains automatically, i.e. it scales automatically with different data sets with different recording time length.
It takes too long to track all codes. That would be great if you could confirm the design principle here. 
Thank you again.

**Comment by epnev** [comment]
The goal is to estimate the noise standard deviation for each pixel and each trace by looking at the PSD of the corresponding time series. Once this is estimated with the code above, then it used as a hard constraint. We estimate the noise level for each observation, not the overall noise for the entire trace. That's why the multiplicative factor sqrt(T) is included.

**Comment by wenxuanliang** [comment]
Exactly. The multiplicative factor sqrt(T) ensures the constrains applies to the standard deviation of the entire trace (i.e. all T samples, i.i.d. assumed, summed together). Sigma in those equations, if I understan it correctly, is still the std of each time point.

**Comment by epnev** [comment]
yes.

**Comment by wenxuanliang** [comment]
But in line 143 and 163 of update_spatial_components.m, the sqrt(T) was multiplied explicitly, which seems to contradict our discussion above.
Line 143: [~, ~, a, ~] = lars_regression_noise(Ytemp(px,fn)', Cf_ds(ind2,fn)', 1, sn_temp(px)^2*T);
Line 163: [~, ~, a, ~] = lars_regression_noise(Y_ds(px,fn)', Cf_ds(ind2,fn)', 1, options.sn(px)^2*T);

This extra constant sqrt(T) might not affect the optimization result much, but it doesn't comply with the theory strictly, if I were not wrong.

**Comment by epnev** [comment]
You want to estimate the vector `a` from a series of `T` observations, where each observation has noise with standard deviation `sn`. So the total noise variance would be sn^2*T, in compliance with the constrained framework that we use.

**Comment by wenxuanliang** [comment]
Yes, but as I discussed above, when calcuting the P.sn using the PSD procedure given by MATLAB, the result has already been scaled by sqrt(T).

To be more specific, psdx = (1/(FsN)) * abs(xdft).^2, gives a power spectrum proportional to N. And then SN{ind} = sqrt(mean(psdx(:,indf)/2,2)) is accordingly scaled by sqrt(N).
As I tested, in the code given by Matheworks, if you increased the sampling period by 10 times, the psd will also increased by 10 times (i.e. 10 dB).

And then in line 143 and 163 of update_spatial_components.m, an extra sqrt(T) is multipled by P.sn.

Did I get anywhere wrong? Happy to further discuss.
Thank you, Dr. Pnevmatikakis.

**Comment by epnev** [comment]
```
>> get_noise_fft(randn(1,1e4))

ans =

    0.9850

>> get_noise_fft(randn(1,1e5))

ans =

    0.9703
```
Answer in both cases is close to 1 (but not exact) and it definitely does not scale with length.

**Comment by wenxuanliang** [comment]
I see the difference here. If you go back to the matheworks script: https://www.mathworks.com/help/signal/ug/power-spectral-density-estimates-using-fft.html, they have:
x = cos(2*pi*100*t) + randn(size(t));

The effective signal peaking at 100Hz will scale with total length, while the randn noise doesn't. 
So for noise calculation, I guess it doesn't matter.
