### ISSUE TITLE
How to tune eta and beta for sparse_NMF_initialization.m

### ISSUE THREAD

**Issue by wenxuanliang** [flatironinstitute/CaImAn-MATLAB#99]
Please note that the developer of this package is on leave until January 2019 and might not be able to support you.

For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**
To use sparse_NMF_initialization for dendritic data processing, any tip on how to tune parameter eta and beta for best performance?

I checked the code, and line 68 of sparse_NMF_initialization.m reads:
    obj = norm(Y - A*C,'fro')^2 + eta*norm(C,'fro')^2 + beta*norm(sum(A,2))^2;
What does this objective function stand for? And why for every 10th iteration, it will run a fmincon optimization? Any explanation on the logic?
Thank you.

**Comment by epnev** [comment]
This sparse NMF formulation follows the objective function proposed in [this paper](https://watermark.silverchair.com/btm134.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAl0wggJZBgkqhkiG9w0BBwagggJKMIICRgIBADCCAj8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQwHRFVjrrZHpg74BAgEQgIICEEY0PDya7JRYn_w8GEM_x0Xt0eQAvt9ewNWI50xyLqNa3EuvSpkcJTK9ZPmqQsox1Ize3jWFRLfJtw3nw8a5Z6ayswvwEXjJYMsS6xNnPtEYvQEdWTXeDSyPs-IEGocoObNESTJO-om8NNrqezuKvG5oWYd0CMFrnSxNwOFhUBNfcfE0-dg4twghFuETPPQIbnf1TfPQyxu29SpwpPragPbOTG64FdPkxojodKq2NoTp5Ym0hOQpgZDVLs52nA3I2c9LOPMoNWanYo7xvFh4cVwLo0jktbE_GYalOsFcZ1dzSJaWdAhdSvL9JwWG8LjdWwCXfTiw9CQc1NSiVcHdrLGVOmIIBdoEg7wF7sVPpR9IQnUUCkH1SyujQ-nYMW08WKWQmi7hMeHRpoA7282H8aFCHISjHus9InNRGUnHXYMPI7AbprZbWsjBrp-4vvz4x-dpNx3oLdhRasO3rXysOV7-64t7EjXPxUYi_sNnn2XINnfb_kPvaey-dIMDesOrRgjTxhikoQyGuCAy1A21vcydpp1o_QJ4VPAj9boSZ9LSlKy7BBbilHdo6QgYqYHAENPAO-3Bx5zvkSC3MU2EVH_CT5Xq4aB8LstERPIZRMX9CGStCgNAVSfP3JuxqXrVVMrgGIjPPoQQprrjNjDWlVIszAVvdUnn3e6F3_POKWaJ7uwZmXDqbVPK5rOCHRW2zQ).  

The intermediate normalization every tenth iteration aims to set a balanced scale between `C` and `A`. For example, `beta < eta` you can always set `C = C/k` and `A = A*k` for `k>1` and decrease the objective function without doing anything useful. The intermediate step is there to avoid this behavior.

Note that this code is somewhat deprecated. For analysis of dendritic data I recommend you use the Python version of CaImAn and the `graph_nmf` initialization method. And in general, the Python version of CaImAn is more actively supported and developed.

**Comment by wenxuanliang** [comment]
Thank you for the detailed explanation! That is very helpful.
The paper link, however, expired before I could check. Would you please share it again, probably just the doi link?

Will try the Python version then. Thank you again.

**Comment by epnev** [comment]
https://doi.org/10.1093/bioinformatics/btm134

**Comment by wenxuanliang** [comment]
Thank you, Dr. Pnevmatikakis.
